# Generated by Django 3.2.4 on 2021-06-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210630_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='categories', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
